#!/bin/sh
set -e
cd /src/app
git clone https://github.com/rackerlabs/insights.git || true
cd insights
git pull origin master || true
pip install -r requirements/development.txt
# clear existing .pyc files
find . -name '*.pyc' -delete